### ISSUE TITLE
Kotlin compiler version out of date

### ISSUE THREAD

**Issue by MlleDelphine** [binaryfoo/emv-bertlv#4]
I don't know if I am at the right place but I'm trying to use your fabulous project but I'm stuck with a compiler error.

For example, in DecodedData.class I have this message when I try to open file : 

```
// This class file was compiled with different version of Kotlin compiler and can't be decompiled.
//
// Current compiler ABI version is 1.0.1
// File ABI version is 0.19.0
```

I'm working on IntelliJ.

Have you got any idea to solve this issue ?

**Comment by MlleDelphine** [comment]
Thanks to a reply from Kotlin forum he library needs to be recompiled with an up-to-date version of Kotlin ! Are you still working and this lib ?

**Comment by wcurrie** [comment]
I've upgraded to kotlin 1.0.0-beta-4589. The tests pass. I'm not confident enough to upgrade [tvr-decoder](http://tvr-decoder.appspot.com/t/home) yet but it's a start.

**Comment by MlleDelphine** [comment]
Nice, I'll try it as soon as possible and I'll get back here to leave a feedback

**Comment by MlleDelphine** [comment]
Ok ! I can open and read mentioned files but I got stuck with RootDecoder class.

When instantiating I got an error : 

 RootDecoder rootDecoder = new RootDecoder();

Throw :

[error] - akka.actor.ActorSystemImpl - Uncaught fatal error from thread [application-akka.actor.default-dispatcher-2] shutting down ActorSystem [application]
java.lang.NoClassDefFoundError: Could not initialize class io.github.binaryfoo.RootDecoder


Any idea ?

**Comment by wcurrie** [comment]
Could I get a little more context please: java version, what else is on you classpath (eg pom.xml or grade build file). Is this the full stack trace. ie e.printStackTrace() rather than just toString() being called on the exception?

A call to new RootDecoder() works fine in [RootDecoderTest](https://github.com/binaryfoo/emv-bertlv/blob/master/src/test/java/io/github/binaryfoo/RootDecoderTest.java) and the code behind the tvr-decoder site ([emv-bertlv-tools](https://github.com/wcurrie/emv-bertlv-tools)).

**Comment by MlleDelphine** [comment]
I use Java8 and my project use sbt so I have a build.sbt file with :

``` 
name := """ProjectName"""

version := "1.0-SNAPSHOT"

lazy val root = (project in file(".")).enablePlugins(PlayJava,PlayEbean)

scalaVersion := "2.11.6"

libraryDependencies ++= Seq(
  javaJdbc,
  cache,
  javaWs,
  ws,
  "mysql" % "mysql-connector-java" % "5.1.36",
  "org.json" % "json" % "20151123"
)

// Play provides two styles of routers, one expects its actions to be injected, the
// other, legacy style, accesses its actions statically.
routesGenerator := InjectedRoutesGenerator
```

Still get the same error.

I only include the emv-bertlv-0.1.5.jar file in my lib directory, import classes needed and error is thrown in IntelliJ Terminal window.

This is the full stack trace. My project uses websocket and return json to browser but nothing is returned and I get this previous error in IntteliJ Terminal. 

Is this clearer to you to find a hint about issue?





fork in run := true

**Comment by wcurrie** [comment]
Hmm I tried a simple project:
https://github.com/wcurrie/emv-bertlv-sbt/tree/master

Instead of using the lib directory can you try just using the maven dependency. ie change your libraryDependencies to:

libraryDependencies ++= Seq(
  javaJdbc,
  cache,
  javaWs,
  ws,
  "mysql" % "mysql-connector-java" % "5.1.36",
  "org.json" % "json" % "20151123",
  "io.github.binaryfoo" % "emv-bertlv" % "0.1.5"
)

**Comment by wcurrie** [comment]
I think there might be a few issues:

1. Including the emv-bertlv by putting it in the lib directory means you don't get transitive depdencies. ie kotlin, snakeyaml and more. Maven's dependency:tree has the full list:

```
emv-bertlv$ mvn dependency:tree -Dscope=compile
...
[INFO] --- maven-dependency-plugin:2.8:tree (default-cli) @ emv-bertlv ---
[INFO] io.github.binaryfoo:emv-bertlv:jar:0.1.6-SNAPSHOT
[INFO] +- commons-lang:commons-lang:jar:2.3:compile
[INFO] +- commons-io:commons-io:jar:2.4:compile
[INFO] +- org.jetbrains.kotlin:kotlin-stdlib:jar:1.0.0-beta-4589:compile
[INFO] |  \- org.jetbrains.kotlin:kotlin-runtime:jar:1.0.0-beta-4589:compile
[INFO] \- org.yaml:snakeyaml:jar:1.14:compile
```

2. Once 1 is resolved by including emv-bertlv using the regular libraryDependencies mechanism there's a version conflict on snakeyaml (issue #5). bertlv is using an older version than play.

With those changes I can run a simple Main class in a play/sbt project...
https://github.com/wcurrie/emv-bertlv-play-framework

**Comment by MlleDelphine** [comment]
Thanks a lot ! Everything is working fine !

Thanks again for time spent and your determination !
