### ISSUE TITLE
Library has Kotlin runtime bundled into it	

### ISSUE THREAD

**Issue by te0tl** [binaryfoo/emv-bertlv#8]
If I use the jar in an Android Studio project I have the following issue:

...app/libs/emv-bertlv-0.1.7-shaded.jar: Library has Kotlin runtime bundled into it |  
-- | --

It's a compile error because the jar it has the runtime libs of kotlin.

"Please note that you should not include kotlin-runtime and kotlin-stdlib jars with your plugin because Kotlin guarantees backward- and forward- binary compatibility."

http://www.jetbrains.org/intellij/sdk/docs/tutorials/kotlin.html

I hope you can fix it or provide a version without the dependency (an not executable version), and thank you so much for the amazing lib.

**Comment by NooAn** [comment]
Yes, I have the same trouble.

**Comment by NooAn** [comment]
So, I found a solution to the problem. I miss extending DexApplication in my release App class.

**Comment by wcurrie** [comment]
Hi. I'm haven't worked on this in ages. Maybe try using non shaded version of the .jar https://repo1.maven.org/maven2/io/github/binaryfoo/emv-bertlv/0.1.7/emv-bertlv-0.1.7.jar
