### ISSUE TITLE
NullPointerException thrown when unpacking data

### ISSUE THREAD

**Issue by icojb25** [binaryfoo/emv-bertlv#9]
Trying to decode the following TLV string, cloned from a working chip card, a NPE is thrown. Parsing the same data using BP-TOOLS EMV tool seems to handle it fine, as does splitting the original string up into two separate substrings (and updating the length bytes). 

"709157134761739001010119D22122011143804400000F5F201A5541542041544D2F5465737420436172642030352020202020205F300202019F1F183131343338303434303030303030303030303030303030309F080200969F4401028C159F02069F03069F1A0295055F2A029A039C019F37048D178A029F02069F03069F1A0295055F2A029A039C019F37049F49039F3704"

Fails with:
raw=[Error] decoded=[Failed parsing TLV with tag 70: Bad length: -1878982400 < 0. Read 8 of 17 (0x91) bytes used to encode length of TLV.] indexes=[0,147]

**Comment by wcurrie** [comment]
Fixed by https://github.com/binaryfoo/emv-bertlv/commit/d49a1801f314f10714b50c292366634f7fe15d93#diff-9c354da30936a2dab18e233b468f309b

I used your example as a test case, which now passes.

I guess some cards use use values 85-FF in the length byte to encode length between of 1

**Comment by wcurrie** [comment]
Now works here too http://tvr-decoder.appspot.com/t/decode/constructed/EMV/709157134761739001010119D22122011143804400000F5F201A5541542041544D2F5465737420436172642030352020202020205F300202019F1F183131343338303434303030303030303030303030303030309F080200969F4401028C159F02069F03069F1A0295055F2A029A039C019F37048D178A029F02069F03069F1A0295055F2A029A039C019F37049F49039F3704

Thanks for the report
